name: Conventional DevOps Pipeline

on:
  push:
    branches: [ main ]

# Permisos requeridos para desplegar a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Pruebas
        run: npm test

      - name: Construir proyecto (Build)
        run: npm run build

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Ajusta según la carpeta de salida (dist, build, out, etc.)

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4